### ISSUE TITLE
install successful but an error occurred

### ISSUE THREAD

**Issue by nichu8** [Bhai4You/Termux-Banner#2]
bash: /data/data/com.termux/files/usr/etc/bash.bashrc: line 15: unexpected EOF while looking for matching `"'
>

**Comment by gitsrk** [comment]
Bro telegram me i have solution @SRS_SRK

**Comment by Bhai4You** [comment]
Remove bash.bashrc file : rm -rvf bash.bashrc
Create New One : touch bash.bashrc
Run Again Termux Banner Script 👍
