### ISSUE TITLE
Nice banner 😘

### ISSUE THREAD

**Issue by Eugenexjay** [Bhai4You/Termux-Banner#35]
Thanks bro, it's really nice. 😁
![Screenshot_20231227-073016.png](https://github.com/Bhai4You/Termux-Banner/assets/120492432/db4ae633-bc9a-4767-b696-eee2d680b6ec)

**Comment by dhalesujal** [comment]
Whose this??

**Comment by Bhai4You** [comment]
Thanks ;)
