### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Midnight1938** [Bhai4You/Termux-Banner#4]
bash: /data/data/com.termux/files/usr/etc/bash.bashrc: line 9: syntax error near unexpected token `('
bash: /data/data/com.termux/files/usr/etc/bash.bashrc: line 9: `cowsay -f eyes _( |@@| | lolcat'

**Comment by Bhai4You** [comment]
× cowsay -f eyes _( |@@| | lolcat'
✓ cowsay -f eyes '_( |@@|' | lolcat

Command :+1: 

cowsay -f eyes 'your name' | lolcat
