### ISSUE TITLE
Termux banner issue always happen to me my banner name change into such numeric code 

### ISSUE THREAD

**Issue by Taruntechme** [Bhai4You/Termux-Banner#5]
![20200404_091337](https://user-images.githubusercontent.com/62782748/78417910-b721d680-7654-11ea-90b0-4a4d47c40ea4.jpg)

**Comment by Taruntechme** [comment]
Can you plz tell me how to solve it

**Comment by Bhai4You** [comment]
Which banner give this issue ? 
maybe you are using Termux Banner 2.0.. if yes then i know there is issue.
